# Generated by Django 4.2.7 on 2023-11-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taken',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taughtby',
            options={'managed': True},
        ),
    ]
